const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.join(__dirname,'..');
const spacer='ACGTACGTACGTACGTACGA';
const donor='A'.repeat(40)+'C'+'G'.repeat(40);
const opposite='C'.repeat(40)+'G'+'T'.repeat(40);
const letters=s=>[...s].map(b=>`<span>${b}</span>`).join('');
function fixture({two=false}={}){return `<h1>Design: Synthetic SNP</h1><h2>2. gRNA Sequences</h2><table><tr><th>Name</th><th>Sequence</th></tr><tr><td>gRNA1</td><td><span>${spacer}</span> <span>TGG</span></td></tr></table><h2>3. Validation Primers</h2><table><tr><td>Primer</td><td>${'T'.repeat(20)}</td></tr></table><h2>4. ssODN Donor Templates</h2><h3>ssODN1</h3><div><div>Order this strand</div><div><div>WT</div><div>${letters('A'.repeat(81))}</div></div><div><div>Donor</div><div>${letters(donor)}</div></div></div><div><div>Reference strand</div><div><div>Donor</div><div>${letters(opposite)}</div></div></div>${two?`<h3>ssODN2</h3><div><div>Donor</div><div>${'T'.repeat(40)+'A'+'G'.repeat(40)}</div></div>`:''}<h2>5. Matched Historical Records</h2><table><tr><td>Historical gRNA</td><td>${'C'.repeat(20)}</td></tr></table>`;}
function environment(){const dom=new JSDOM(fs.readFileSync(path.join(root,'public/index.html'),'utf8'),{runScripts:'outside-only',url:'http://localhost'});for(const file of ['design-import.js','app.js','design-workflow.js'])require('node:vm').runInContext(fs.readFileSync(path.join(root,'public',file),'utf8'),dom.getInternalVMContext());return dom;}
test('import annotated donor, omit PAM/WT/primers/history, deduplicate opposite strand',()=>{const dom=environment();const [d]=dom.window.TraceEditDesign.parse(fixture());assert.equal(d.guides.length,1);assert.equal(d.guides[0].sequence,spacer);assert.equal(d.donors.length,1);assert.equal(d.donors[0].sequence,donor);assert.equal(d.donors[0].recommended,true);dom.window.close();});
test('retain distinct donor choices and separate batch designs',()=>{const dom=environment();const ds=dom.window.TraceEditDesign.parse(fixture({two:true})+fixture());assert.equal(ds.length,2);assert.equal(ds[0].donors.length,2);assert.equal(ds[1].donors.length,1);dom.window.close();});
test('KO report imports guides without a donor',()=>{const dom=environment();const html=fixture().split('<h2>4.')[0]+'<h2>4. Knockout Design</h2><p>No donor required.</p>';assert.equal(dom.window.TraceEditDesign.parse(html)[0].donors.length,0);dom.window.close();});
test('unrecognized reports rejected; embedded code never executes',()=>{const dom=environment();assert.throws(()=>dom.window.TraceEditDesign.parse('<p>not a design</p>'),/No supported/);dom.window.TraceEditDesign.parse(fixture()+'<script>globalThis.compromised=true</script><img src="https://invalid.test/private" onerror="globalThis.compromised=true">');assert.equal(dom.window.compromised,undefined);assert.equal(dom.window.document.querySelector('img'),null);dom.window.close();});
test('typing donor with whitespace maps without requiring sample reads',async()=>{const dom=environment(),w=dom.window;Object.defineProperty(w.document.getElementById('control'),'files',{value:[new w.File(['ABIF'],'control.ab1')]});w.document.getElementById('donor').value='a'.repeat(40)+'\n c '+'g'.repeat(40);w.fetch=async(url,options)=>{assert.equal(url,'/api/donor');assert.equal(options.body.get('donor'),donor);return {ok:true,json:async()=>({strand:'+',coverage:1,variants:[{position:247,ref:'A',alt:'C'}]})};};await w.document.getElementById('map-donor').onclick();assert.equal(w.document.getElementById('variants').value,'A247C');assert.match(w.document.getElementById('donor-status').textContent,/Mapped 1/);dom.window.close();});
test('analysis automatically maps donor before sending SNP settings',async()=>{const dom=environment(),w=dom.window;for(const id of ['control','samples'])Object.defineProperty(w.document.getElementById(id),'files',{value:[new w.File(['ABIF'],id+'.ab1')]});w.document.getElementById('donor').value=donor;w.document.getElementById('cuts').value='240';const calls=[];w.fetch=async(url,options)=>{calls.push(url);if(url==='/api/donor')return {ok:true,json:async()=>({strand:'+',coverage:1,variants:[{position:247,ref:'A',alt:'C'}]})};assert.equal(JSON.parse(options.body.get('settings')).variants[0].alt,'C');return {ok:true,json:async()=>({sample:'synthetic',status:'failed',error:'Synthetic stub response'})};};await w.document.getElementById('analysis-form').onsubmit({preventDefault(){}});assert.deepEqual(calls,['/api/donor','/api/analyze']);dom.window.close();});
test('failed donor mapping stops analysis instead of silently running KO',async()=>{const dom=environment(),w=dom.window;Object.defineProperty(w.document.getElementById('control'),'files',{value:[new w.File(['ABIF'],'control.ab1')]});w.document.getElementById('donor').value=donor;let calls=0;w.fetch=async()=>{calls++;return {ok:false,json:async()=>({error:'Donor alignment failed'})};};await w.document.getElementById('analysis-form').onsubmit({preventDefault(){}});assert.equal(calls,1);assert.match(w.document.getElementById('error').textContent,/alignment failed/);dom.window.close();});
test('import fills visible fields and clears stale cut/SNP coordinates',async()=>{const dom=environment(),w=dom.window,doc=w.document;doc.getElementById('cuts').value='999';doc.getElementById('variants').value='C888T';Object.defineProperty(doc.getElementById('design-file'),'files',{value:[{size:1000,text:async()=>fixture({two:true})}]});await doc.getElementById('design-file').onchange();assert.equal(doc.getElementById('guides').value,spacer);assert.equal(doc.getElementById('donor').value,donor);assert.equal(doc.getElementById('cuts').value,'');assert.equal(doc.getElementById('variants').value,'');assert.equal(doc.getElementById('donor-choice-label').hidden,false);doc.getElementById('donor-choice').value='1';doc.getElementById('donor-choice').onchange();assert.equal(doc.getElementById('donor').value,'T'.repeat(40)+'A'+'G'.repeat(40));dom.window.close();});
