const test=require('node:test'),assert=require('node:assert/strict');
const core=()=>import('../public/unified/core.js');
function result(){return {target:{position:40,ref:'A',alt:'G'},aq:{ok:true,controlHash:'c',sampleHash:'s',summary:{indelPct:0},r2:.99,markers:[{position:40,ref:'A',alt:'G',covered:true,inFit:true,raw:.55}],warnings:[]},te:{source_hashes:{control:'c',sample:'s'},metrics:{indel_fraction:0,r_squared:.99},variants:[{position:40,ref:'A',alt:'G',sample_alt_signal:.54}],warnings:[]}};}
test('comparison never averages and requires matching source bytes',async()=>{const {compare}=await core();const r=result();assert.equal(compare(r).label,'Similar estimates');r.te.source_hashes.sample='other';assert.equal(compare(r).label,'Input mismatch');});
test('disagreement, missing SNP, indels and failed engines require review',async()=>{const {compare}=await core();let r=result();r.te.variants[0].sample_alt_signal=.1;assert.equal(compare(r).label,'Review engine difference');r=result();r.aq.markers[0].inFit=false;assert.equal(compare(r).label,'QC review');r=result();r.te.metrics.indel_fraction=.12;assert.equal(compare(r).label,'QC review');r=result();r.aq={ok:false,error:'bad trace'};assert.equal(compare(r).label,'Incomplete');});
test('same input setup only supports the intersection of engine capabilities',async()=>{const {validateSetup}=await core();const s={name:'Test',gene:'Test',primer:'forward',guides:['ACGT'.repeat(5)],donor:'',workflow:'knockout'};assert.doesNotThrow(()=>validateSetup(s));assert.throws(()=>validateSetup({...s,workflow:'snp'}),/donor/);assert.throws(()=>validateSetup({...s,donor:'A'.repeat(301)}),/30–300/);assert.throws(()=>validateSetup({...s,guides:['ACGT']}),/20-base/);});
test('CSV escapes spreadsheet formulas and report escapes imported text',async()=>{const {csv}=await core();assert.match(csv([['=1+1','normal']]),/'=1\+1/);const {reportHtml}=await import('../public/unified/report.js');const r=result();r.sample='<script>alert(1)</script>';r.control='c';const html=reportHtml({setup:{name:'<img>',gene:'TEST'},results:[r],planned:1,engines:{}});assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('0.85'));});

test('multi-target comparisons check every intended base and report all sites',async()=>{const {compare}=await core();const {reportHtml}=await import('../public/unified/report.js');const r=result();r.targets=[r.target,{position:41,ref:'C',alt:'A'}];r.aq.markers.push({...r.targets[1],covered:true,inFit:true,raw:.5,corrected:.5});r.te.variants.push({...r.targets[1],sample_alt_signal:.1,background_corrected_signal:.1});assert.equal(compare(r).label,'Review engine difference');const html=reportHtml({setup:{name:'pool',sampleType:'pool'},results:[r],planned:1,engines:{}});assert.match(html,/C41A/);assert.match(html,/co-occurrence/);assert.match(html,/Per-base evidence/);r.aq.markers[1].inFit=false;assert.equal(compare(r).label,'QC review');});
test('two substitution donors validate without concatenating their sequences',async()=>{const {validateSetup}=await core();const s={name:'pool',gene:'G',primer:'P',guides:['ACGT'.repeat(5)],donors:['A'.repeat(127),'C'.repeat(127)],workflow:'snp'};assert.doesNotThrow(()=>validateSetup(s));assert.throws(()=>validateSetup({...s,donors:[...s.donors,'G'.repeat(127)]}));});
