const test=require('node:test'),assert=require('node:assert/strict');
const core=()=>import('../public/unified/core.js');
const imports=()=>import('../public/unified/imports.js');
function result(){return {target:{position:40,ref:'A',alt:'G'},aq:{ok:true,controlHash:'c',sampleHash:'s',summary:{indelPct:0},r2:.99,markers:[{position:40,ref:'A',alt:'G',covered:true,inFit:true,raw:.55}],warnings:[]},te:{source_hashes:{control:'c',sample:'s'},metrics:{indel_fraction:0,r_squared:.99},variants:[{position:40,ref:'A',alt:'G',sample_alt_signal:.54}],warnings:[]}};}
test('comparison never averages and requires matching source bytes',async()=>{const {compare}=await core();const r=result();assert.equal(compare(r).label,'Similar estimates');r.te.source_hashes.sample='other';assert.equal(compare(r).label,'Input mismatch');});
test('disagreement, missing SNP, indels and failed engines require review',async()=>{const {compare}=await core();let r=result();r.te.variants[0].sample_alt_signal=.1;assert.equal(compare(r).label,'Review engine difference');r=result();r.aq.markers[0].inFit=false;assert.equal(compare(r).label,'QC review');r=result();r.te.metrics.indel_fraction=.12;assert.equal(compare(r).label,'QC review');r=result();r.aq={ok:false,error:'bad trace'};assert.equal(compare(r).label,'Incomplete');});
test('same input setup only supports the intersection of engine capabilities',async()=>{const {validateSetup}=await core();const s={name:'Test',gene:'Test',primer:'forward',guides:['ACGT'.repeat(5)],donor:'',workflow:'knockout'};assert.doesNotThrow(()=>validateSetup(s));assert.throws(()=>validateSetup({...s,workflow:'snp'}),/donor/);assert.throws(()=>validateSetup({...s,donor:'A'.repeat(301)}),/30–300/);assert.throws(()=>validateSetup({...s,guides:['ACGT']}),/20-base/);});
test('LAGESO import uses header row and preserves separate source rows',async()=>{const {projectsFromSheets}=await imports();const headers=['Lfd.Nr.','Parental Cell Line / Donor','sgRNA / Targeting Sequence','Target Gene (NCBI/ENSEMBL ID)','Donor Seq / ssODN','Cell Line Name (hPSCreg)','Modification Type'];const rows=[{number:1,values:['Title']},{number:3,values:headers},{number:4,values:['Proj3.1','parent','gRNA1: '+ 'ACGT'.repeat(5),'TEST','Donor: '+'AGCT'.repeat(20),'clone','KI']},{number:5,values:['Proj3.1','parent','gRNA1: '+ 'ACGT'.repeat(5),'TEST','N/A (KO)','clone2','KO']}];const out=projectsFromSheets([{name:'Registry',rows}]);assert.equal(out.length,2);assert.notEqual(out[0].id,out[1].id);assert.equal(out[0].guides[0].sequence.length,20);assert.equal(out[0].donors[0].sequence.length,80);assert.equal(out[1].donors.length,0);assert.equal(out[0].source.row,4);assert.throws(()=>projectsFromSheets([{name:'empty',rows:[]}]),/No LAGESO/);});
test('sequence extraction excludes labels and joins multiline donor DNA',async()=>{const {sequences}=await imports();assert.equal(sequences('gRNA: '+ 'ACGT'.repeat(5)+' TGG','guide')[0].sequence,'ACGT'.repeat(5));assert.equal(sequences('donor: '+'A'.repeat(20)+'\n'+'C'.repeat(20),'donor')[0].sequence,'A'.repeat(20)+'C'.repeat(20));assert.equal(sequences('N/A (KO)','donor').length,0);});
test('CSV escapes spreadsheet formulas and report escapes imported text',async()=>{const {csv}=await core();assert.match(csv([['=1+1','normal']]),/'=1\+1/);const {reportHtml}=await import('../public/unified/report.js');const r=result();r.sample='<script>alert(1)</script>';r.control='c';const html=reportHtml({setup:{name:'<img>',gene:'TEST'},results:[r],planned:1,engines:{}});assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('0.85'));});
